### ISSUE TITLE
mprof plot - IndexError: tuple index out of range

### ISSUE THREAD

**Issue by oesteban** [pythonprofilers/memory_profiler#136]
I'm seeing this IndexError with python 2.7 and python 3.5 using the pypi latest version.

```
Using last profile data.
Traceback (most recent call last):
  File "/home/oesteban/miniconda2/envs/nipypedev-3.5/bin/mprof", line 551, in <module>
    actions[get_action()]()
  File "/home/oesteban/miniconda2/envs/nipypedev-3.5/bin/mprof", line 517, in plot_action
    mprofile = plot_file(filename, index=n, timestamps=timestamps, options=options)
  File "/home/oesteban/miniconda2/envs/nipypedev-3.5/bin/mprof", line 415, in plot_file
    pl.plot(cts, cmem, "+-"  + mem_line_colors[idx+1 % len(mem_line_colors)],
IndexError: tuple index out of range
```

**Comment by fabianp** [comment]
Thanks for the report. I found a silly mistake in mprof but I've pushed a fix and made a new release. Could you please update your version (pip install -U memory_profiler) and let me know if this fixes the problem?

**Comment by oesteban** [comment]
Thanks for the prompt answer.

I have tried new 0.45 release and I still see this problem.

I can make a development installation from any branch you point me to, if you want quicker iterations on this.

The file I'm trying to plot is here: https://gist.github.com/oesteban/19838464861736bd2d861f2f96e2f56a#file-mprofile_20170324074440-dat

**Comment by Juanlu001** [comment]
I tried running `mprof plot mprofile_20170324074440.dat` cannot reproduce this issue with the latest version from master and Python 3.6. I am closing, please comment if the problem persists.
